using Gambit.App.Services;
using Gambit.Core.Puzzles;
using Microsoft.UI.Text;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Navigation;

namespace Gambit.App.Pages;

/// <summary>Puzzle hub: rating and rank, rated puzzles, daily puzzle, Puzzle Rush, theme practice.</summary>
public sealed partial class PuzzlesPage : Page
{
    private static readonly string[] ThemeOrder =
    [
        "mateIn1", "mateIn2", "mateIn3", "mateIn4", "fork", "pin", "discoveredAttack", "hangingPiece",
        "sacrifice", "backRankMate", "smotheredMate", "promotion", "opening", "middlegame", "endgame",
    ];

    public PuzzlesPage() => InitializeComponent();

    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);
        PuzzleService svc = PuzzleService.Instance;
        PuzzleProfile p = svc.Profile;
        int total = svc.All.Count;

        Subtitle.Text = total == 0
            ? "The puzzle collection is not installed in this build."
            : $"{total:N0} puzzles, from one-move tactics to deep combinations.";

        var (rank, floor, next) = PuzzleService.Rank(p.Rating);
        RankName.Text = $"{rank} rank";
        RankGlyph.Text = rank switch
        {
            "Pawn" => "♟",
            "Knight" => "♞",
            "Bishop" => "♝",
            "Rook" => "♜",
            "Queen" => "♛",
            _ => "♚",
        };
        RatingText.Text = $"{Math.Round(p.Rating):0}{(p.Deviation > 110 ? "?" : "")}";
        RankProgress.Value = Math.Clamp((p.Rating - floor) / Math.Max(1, next - floor), 0, 1);
        RankHint.Text = rank == "Grandmaster" ? "Top rank reached." : $"{Math.Max(0, next - (int)p.Rating)} points to the next rank";
        SolvedText.Text = p.Solved.ToString("N0");
        SuccessText.Text = p.Attempts == 0 ? "—" : $"{100.0 * p.Solved / p.Attempts:0}%";
        StreakText.Text = $"{p.CurrentStreak} ({p.BestStreak})";

        string today = DateTime.Now.ToString("yyyy-MM-dd");
        bool doneToday = p.LastDailyDate == today;
        DailyText.Text = doneToday
            ? $"Done for today. Daily streak: {p.DailyStreak} day{(p.DailyStreak == 1 ? "" : "s")}."
            : $"A new puzzle every day. Current streak: {p.DailyStreak} day{(p.DailyStreak == 1 ? "" : "s")}.";
        DailyButton.Content = doneToday ? "Play it again" : "Solve today's puzzle";

        Best3.Text = p.BestRush3 > 0 ? $"Best {p.BestRush3}" : "—";
        Best5.Text = p.BestRush5 > 0 ? $"Best {p.BestRush5}" : "—";
        BestSurvival.Text = p.BestSurvival > 0 ? $"Best {p.BestSurvival}" : "—";

        BuildThemes(svc, p);
        SourceNote.Text = "Puzzles are generated by Gambit's own engine from thousands of computer games: each has a single clearly best line, verified by deep search.";
    }

    private void BuildThemes(PuzzleService svc, PuzzleProfile p)
    {
        ThemeGrid.Children.Clear();
        foreach (string theme in ThemeOrder)
        {
            int count = svc.All.Count(z => z.HasTheme(theme));
            if (count == 0) continue;
            p.Themes.TryGetValue(theme, out ThemeStat? stat);

            var stack = new StackPanel { Spacing = 2 };
            stack.Children.Add(new TextBlock { Text = PuzzleThemes.Name(theme), FontWeight = FontWeights.SemiBold });
            stack.Children.Add(new TextBlock
            {
                Text = stat is { Attempts: > 0 }
                    ? $"{count} puzzles · {100.0 * stat.Solved / stat.Attempts:0}% solved"
                    : $"{count} puzzles",
                FontSize = 12,
                Opacity = 0.7,
            });
            var button = new Button
            {
                Content = stack,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Stretch,
                HorizontalContentAlignment = HorizontalAlignment.Left,
                Margin = new Thickness(0, 0, 8, 8),
                Padding = new Thickness(14, 8, 14, 8),
            };
            Microsoft.UI.Xaml.Automation.AutomationProperties.SetName(button, $"Practice {PuzzleThemes.Name(theme)}");
            button.Click += (_, _) => Start(new PuzzleRequest(PuzzleMode.Theme, theme));
            ThemeGrid.Children.Add(button);
        }
    }

    private static void Start(PuzzleRequest request) => App.Window.Navigate(typeof(PuzzleSolvePage), request, "puzzles");

    private void Rated_Click(object sender, RoutedEventArgs e) => Start(new PuzzleRequest(PuzzleMode.Rated));
    private void Daily_Click(object sender, RoutedEventArgs e) => Start(new PuzzleRequest(PuzzleMode.Daily));
    private void Rush3_Click(object sender, RoutedEventArgs e) => Start(new PuzzleRequest(PuzzleMode.Rush3));
    private void Rush5_Click(object sender, RoutedEventArgs e) => Start(new PuzzleRequest(PuzzleMode.Rush5));
    private void Survival_Click(object sender, RoutedEventArgs e) => Start(new PuzzleRequest(PuzzleMode.Survival));
}
