using System.Runtime.InteropServices;
using Gambit.Core.Games;

namespace Gambit.App.Services;

public enum GameSound
{
    Move,
    Capture,
    Castle,
    Check,
    Promote,
    Start,
    Win,
    End,
    Illegal,
    LowTime,
}

/// <summary>
/// Plays the synthesized sound effects (Assets/Sounds, generated by tools/gen_sounds.py) with the
/// Win32 PlaySound API: tiny latency, no dependencies, works unpackaged on Arm64. The classic pack is
/// Assets/Sounds itself; each other pack is a subfolder with the same file names.
/// </summary>
public static partial class SoundService
{
    private const uint SndAsync = 0x0001;
    private const uint SndNoDefault = 0x0002;
    private const uint SndFilename = 0x00020000;

    [LibraryImport("winmm.dll", EntryPoint = "PlaySoundW", StringMarshalling = StringMarshalling.Utf16)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool PlaySound(string? sound, IntPtr module, uint flags);

    private static readonly string Folder = Path.Combine(AppContext.BaseDirectory, "Assets", "Sounds");

    /// <summary>The sound packs Settings offers, in order: (id, name).</summary>
    public static IReadOnlyList<(string Id, string Name)> Packs { get; } = [("classic", "Classic"), ("soft", "Soft"), ("retro", "Retro")];

    public static void Play(GameSound sound)
    {
        if (!App.Settings.Current.SoundEnabled) return;
        string file = FileFor(sound, App.Settings.Current.SoundPack);
        if (!File.Exists(file)) return;
        try
        {
            PlaySound(file, IntPtr.Zero, SndAsync | SndNoDefault | SndFilename);
        }
        catch (Exception ex)
        {
            Log.Warn($"Sound failed: {ex.Message}");
        }
    }

    /// <summary>A few sounds of the chosen pack in a row, so Settings can let you hear it.</summary>
    public static async Task PlaySampleAsync()
    {
        foreach (GameSound sound in new[] { GameSound.Move, GameSound.Capture, GameSound.Check })
        {
            Play(sound);
            await Task.Delay(420);
        }
    }

    private static string FileFor(GameSound sound, string? pack)
    {
        string name = sound.ToString().ToLowerInvariant() + ".wav";
        if (pack != Packs[0].Id && Packs.Any(p => p.Id == pack))
        {
            string packed = Path.Combine(Folder, pack!, name);
            if (File.Exists(packed)) return packed;
        }
        return Path.Combine(Folder, name);
    }

    /// <summary>The right sound for a move that was just played.</summary>
    public static void PlayFor(GameMove move)
    {
        if (move.GivesCheck) Play(GameSound.Check);
        else if (move.Move.IsPromotion) Play(GameSound.Promote);
        else if (move.Move.IsCastle) Play(GameSound.Castle);
        else if (move.Move.IsCapture) Play(GameSound.Capture);
        else Play(GameSound.Move);
    }
}
