using System.Runtime.InteropServices;
using Gambit.Core.Games;

namespace Gambit.App.Services;

public enum GameSound
{
    Move,
    Capture,
    Castle,
    Check,
    Promote,
    Start,
    Win,
    End,
    Illegal,
    LowTime,
}

/// <summary>
/// Plays the synthesized sound effects (Assets/Sounds, generated by tools/gen_sounds.py) with the
/// Win32 PlaySound API: tiny latency, no dependencies, works unpackaged on Arm64.
/// </summary>
public static partial class SoundService
{
    private const uint SndAsync = 0x0001;
    private const uint SndNoDefault = 0x0002;
    private const uint SndFilename = 0x00020000;

    [LibraryImport("winmm.dll", EntryPoint = "PlaySoundW", StringMarshalling = StringMarshalling.Utf16)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool PlaySound(string? sound, IntPtr module, uint flags);

    private static readonly string Folder = Path.Combine(AppContext.BaseDirectory, "Assets", "Sounds");

    public static void Play(GameSound sound)
    {
        if (!App.Settings.Current.SoundEnabled) return;
        string file = Path.Combine(Folder, sound.ToString().ToLowerInvariant() + ".wav");
        if (!File.Exists(file)) return;
        try
        {
            PlaySound(file, IntPtr.Zero, SndAsync | SndNoDefault | SndFilename);
        }
        catch (Exception ex)
        {
            Log.Warn($"Sound failed: {ex.Message}");
        }
    }

    /// <summary>The right sound for a move that was just played.</summary>
    public static void PlayFor(GameMove move)
    {
        if (move.GivesCheck) Play(GameSound.Check);
        else if (move.Move.IsPromotion) Play(GameSound.Promote);
        else if (move.Move.IsCastle) Play(GameSound.Castle);
        else if (move.Move.IsCapture) Play(GameSound.Capture);
        else Play(GameSound.Move);
    }
}
